<template>
  <div v-if="toc.length" class="flex-none hidden w-64 pl-8 mr-8 xl:text-sm xl:block">
    <div class="flex flex-col justify-between overflow-y-auto sticky max-h-(screen-18) -mt-10 pt-10 pb-4 top-18">
      <div class="mb-8">
        <h5 class="mb-3 text-sm font-semibold tracking-wide text-gray-900 uppercase dark:text-gray-100 lg:text-xs">{{ $t('toc.title') }}</h5>

        <ul class="overflow-x-hidden font-medium">
          <li
            v-for="link of toc"
            :key="link.id"
            class="hover:text-gray-900 dark:hover:text-gray-100"
            :class="{ 'text-primary-500 hover:text-primary-500 dark:text-primary-400 dark:hover:text-primary-400': activeLink === link.id }"
          >
            <a
              :href="`#${link.id}`"
              class="block py-2 transition-colors duration-100 transform scrollactive-item"
              :class="{
                'ml-2': link.depth === 3,
                'ml-3': link.depth === 4,
                'ml-4': link.depth === 5,
                'ml-5': link.depth === 6
              }"
            >{{ link.text }}</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    toc: {
      type: Array,
      default: () => []
    }
  },
  data () {
    return {
      activeLink: ''
    }
  },
  computed: {
    settings () {
      return this.$docus.settings
    }
  },
  mounted () {
    if (window.IntersectionObserver) {
      this.observer = new IntersectionObserver((entries) => {
        entries.forEach((entry) => {
          const id = entry.target.getAttribute('id')
          if (entry.isIntersecting) {
            this.activeLink = id
          }
        })
      }, { threshold: 1 })
      // Track all titles generated by nuxt-content and displayed in the TOC
      document
        .querySelectorAll('.nuxt-content h2[id], .nuxt-content h3[id]')
        .forEach((section) => {
          this.observer.observe(section)
        })
    }
  },
  beforeDestroy () {
    if (this.observer) {
      this.observer.disconnect()
      delete this.observer
    }
  }
}
</script>
