<template>
  <Link :to="href" :blank="blank">
    <slot />
  </Link>
</template>

<script>
import { defineComponent } from '@nuxtjs/composition-api'

export default defineComponent({
  props: {
    href: {
      type: String,
      default: ''
    },
    blank: {
      type: Boolean,
      default: false
    },
    /**
     * `true` if `href` points to a static file
     */
    static: {
      type: Boolean,
      default: false
    }
  }
})
</script>

<style lang="postcss" scoped>
:not(h1, h2, h3, h4) > a {
  /* TODO: shouldn't rely on autogenerated CSS vars? */
  color: var(--primary-500);
  font-weight: theme('fontWeight.medium');
  text-decoration: none;
  &:hover {
    border-bottom-width: 1px;
    border-bottom-color: var(--primary-500);
    padding-bottom: 1px;
  }
}

.dark :not(h1, h2, h3, h4) > a {
  color: var(--primary-400);
  &:hover {
    border-bottom-color: var(--primary-400);
  }
}

h1 a,
h2 a,
h3 a,
h4 a {
  position: relative;
  /* &:hover {
    border-bottom-width: 0px;
    padding-bottom: 0px;
  } */
  &::after {
    content: url('data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="%23111827"%3E%3Cpath stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" /%3E%3C/svg%3E');
    position: absolute;
    padding-left: theme('padding.2');
    width: theme('spacing.5');
    height: theme('spacing.5');
    opacity: 0;
  }
  &:hover {
    &::after {
      opacity: 1;
    }
  }
  &:before {
    content: '';
    position: absolute;
    top: 0px;
    left: 0px;
    width: 100%;
    height: calc(100% + 4px);
  }
  &:hover:before {
    border-bottom-width: 1px;
    border-style: dashed;
    border-bottom-color: theme('colors.gray.900');
  }
}

.dark h1 a,
.dark h2 a,
.dark h3 a,
.dark h4 a {
  &:hover {
    &:before {
      border-bottom-color: theme('colors.gray.100');
    }
  }
  &::after {
    content: url('data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="white"%3E%3Cpath stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" /%3E%3C/svg%3E');
  }
}
</style>
